INSERT INTO PLAYERS (name) VALUES ('Viktor');
INSERT INTO PLAYERS (name) VALUES ('Ivan');
INSERT INTO PLAYERS (name) VALUES ('Masha');
INSERT INTO PLAYERS (name) VALUES ('Anna');
INSERT INTO PLAYERS (name) VALUES ('Misha');
INSERT INTO PLAYERS (name) VALUES ('Vlad');
INSERT INTO PLAYERS (name) VALUES ('Alexander');
INSERT INTO PLAYERS (name) VALUES ('Maksim');

INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (1,2,1);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (2,3,2);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (4,5,4);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (5,6,6);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (6,7,6);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (7,8,7);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (8,1,1);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (1,3,3);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (1,4,1);
INSERT INTO MATCHES (FIRSTPLAYER, SECONDPLAYER, WINNER) VALUES (1,5,5);